### ISSUE TITLE
Failed to assign partitions to X messages

### ISSUE THREAD

**Issue by J2RGEZ** [zendesk/ruby-kafka#678]
If this is a bug report, please fill out the following:

* Version of Ruby: 2.4.0
* Version of Kafka: 0.9.0.1
* Version of ruby-kafka: 0.4.4

###### Steps to reproduce
I just want to produce messages.
```ruby
@kafka_client = Kafka.new(seed_brokers: [
      "localhost:9092",
      "localhost:9093",
      "localhost:9094"],
      client_id: "Test_app", logger: Logger.new(STDOUT))
    producer = @kafka_client.producer
    producer.produce("Hello Test!!", topic: "test1")
    producer.produce("Bye Test!!", topic: "test2")
    producer.deliver_messages
```

###### Expected outcome

Produced message

###### Actual outcome
```
I, [2018-11-05T11:35:47.357338 #8804]  INFO -- : New topics added to target list: test1, test2
I, [2018-11-05T11:35:47.357519 #8804]  INFO -- : Fetching cluster metadata from kafka://localhost:9094
D, [2018-11-05T11:35:47.357670 #8804] DEBUG -- : Opening connection to localhost:9094 with client id Test_app...
D, [2018-11-05T11:35:47.358201 #8804] DEBUG -- : Sending request 1 to localhost:9094
D, [2018-11-05T11:35:47.358495 #8804] DEBUG -- : Waiting for response 1 from localhost:9094
D, [2018-11-05T11:35:47.521561 #8804] DEBUG -- : Received response 1 from localhost:9094
I, [2018-11-05T11:35:47.521713 #8804]  INFO -- : Discovered cluster metadata; nodes: 
D, [2018-11-05T11:35:47.521792 #8804] DEBUG -- : Closing socket to localhost:9094
I, [2018-11-05T11:35:47.522523 #8804]  INFO -- : Fetching cluster metadata from kafka://localhost:9092
D, [2018-11-05T11:35:47.522647 #8804] DEBUG -- : Opening connection to localhost:9092 with client id Test_app...
D, [2018-11-05T11:35:47.523204 #8804] DEBUG -- : Sending request 1 to localhost:9092
D, [2018-11-05T11:35:47.523394 #8804] DEBUG -- : Waiting for response 1 from localhost:9092
D, [2018-11-05T11:35:47.629863 #8804] DEBUG -- : Received response 1 from localhost:9092
I, [2018-11-05T11:35:47.629960 #8804]  INFO -- : Discovered cluster metadata; nodes: 
D, [2018-11-05T11:35:47.630014 #8804] DEBUG -- : Closing socket to localhost:9092
E, [2018-11-05T11:35:47.630493 #8804] ERROR -- : Failed to assign partitions to 1 messages in test1
E, [2018-11-05T11:35:47.630557 #8804] ERROR -- : Failed to assign partitions to 1 messages in test2
W, [2018-11-05T11:35:47.630656 #8804]  WARN -- : Failed to send all messages; attempting retry 1 of 2 after 1s
I, [2018-11-05T11:35:48.630882 #8804]  INFO -- : Fetching cluster metadata from kafka://localhost:9094
D, [2018-11-05T11:35:48.631161 #8804] DEBUG -- : Opening connection to localhost:9094 with client id Test_app...
D, [2018-11-05T11:35:48.632064 #8804] DEBUG -- : Sending request 1 to localhost:9094
D, [2018-11-05T11:35:48.632422 #8804] DEBUG -- : Waiting for response 1 from localhost:9094
D, [2018-11-05T11:35:48.645893 #8804] DEBUG -- : Received response 1 from localhost:9094
I, [2018-11-05T11:35:48.645981 #8804]  INFO -- : Discovered cluster metadata; nodes: 
D, [2018-11-05T11:35:48.646014 #8804] DEBUG -- : Closing socket to localhost:9094
I, [2018-11-05T11:35:48.646538 #8804]  INFO -- : Fetching cluster metadata from kafka://localhost:9094
D, [2018-11-05T11:35:48.646683 #8804] DEBUG -- : Opening connection to localhost:9094 with client id Test_app...
D, [2018-11-05T11:35:48.647116 #8804] DEBUG -- : Sending request 1 to localhost:9094
D, [2018-11-05T11:35:48.647359 #8804] DEBUG -- : Waiting for response 1 from localhost:9094
D, [2018-11-05T11:35:48.654627 #8804] DEBUG -- : Received response 1 from localhost:9094
I, [2018-11-05T11:35:48.654754 #8804]  INFO -- : Discovered cluster metadata; nodes: 
D, [2018-11-05T11:35:48.654842 #8804] DEBUG -- : Closing socket to localhost:9094
E, [2018-11-05T11:35:48.655548 #8804] ERROR -- : Failed to assign partitions to 1 messages in test1
E, [2018-11-05T11:35:48.655624 #8804] ERROR -- : Failed to assign partitions to 1 messages in test2
W, [2018-11-05T11:35:48.655728 #8804]  WARN -- : Failed to send all messages; attempting retry 2 of 2 after 1s
I, [2018-11-05T11:35:49.655970 #8804]  INFO -- : Fetching cluster metadata from kafka://localhost:9094
D, [2018-11-05T11:35:49.656236 #8804] DEBUG -- : Opening connection to localhost:9094 with client id Test_app...
D, [2018-11-05T11:35:49.657044 #8804] DEBUG -- : Sending request 1 to localhost:9094
D, [2018-11-05T11:35:49.657581 #8804] DEBUG -- : Waiting for response 1 from localhost:9094
D, [2018-11-05T11:35:49.668004 #8804] DEBUG -- : Received response 1 from localhost:9094
I, [2018-11-05T11:35:49.668130 #8804]  INFO -- : Discovered cluster metadata; nodes: 
D, [2018-11-05T11:35:49.668229 #8804] DEBUG -- : Closing socket to localhost:9094
I, [2018-11-05T11:35:49.669090 #8804]  INFO -- : Fetching cluster metadata from kafka://localhost:9092
D, [2018-11-05T11:35:49.669374 #8804] DEBUG -- : Opening connection to localhost:9092 with client id Test_app...
D, [2018-11-05T11:35:49.670464 #8804] DEBUG -- : Sending request 1 to localhost:9092
D, [2018-11-05T11:35:49.670816 #8804] DEBUG -- : Waiting for response 1 from localhost:9092
D, [2018-11-05T11:35:49.677564 #8804] DEBUG -- : Received response 1 from localhost:9092
I, [2018-11-05T11:35:49.677677 #8804]  INFO -- : Discovered cluster metadata; nodes: 
D, [2018-11-05T11:35:49.677757 #8804] DEBUG -- : Closing socket to localhost:9092
E, [2018-11-05T11:35:49.678326 #8804] ERROR -- : Failed to assign partitions to 1 messages in test1
E, [2018-11-05T11:35:49.678396 #8804] ERROR -- : Failed to assign partitions to 1 messages in test2
E, [2018-11-05T11:35:49.678490 #8804] ERROR -- : Failed to send all messages; keeping remaining messages in buffer
Completed 500 Internal Server Error in 4660ms (ActiveRecord: 0.9ms)
```

I've tried with 0.9.x and ruby-kafka 0.4.x. Also with 0.10.x and ruby-kafka 0.5.x as specified in the compatibility table but it's not working in any of those versions.

**Comment by nguyenquangminh0711** [comment]
Hi @J2RGEZ, your example is trivial, and that's actually covered by the test suite of ruby kafka. So, I don't think that would be a problem of ruby-kafka. There are something you can try to debug this issue:
- Which advertising host are your kafka servers binding on? Usually, if they binds on specific interface, the connection to other interface are rejected. A common mistake is that the servers bind on 127.0.0.1 will rejects connection calling to localhost. If you bind on 0.0.0.0, it will accept all interfaces.
- Are you running in docker? Did you expose the ports to outside environment? 
- Did you try to connect to your kafka servers by using Kafka command lines, or clients in other languages?

Hope that would help you.

**Comment by nguyenquangminh0711** [comment]
Hi @J2RGEZ, your use case is trivial and actually covered by the test suite of ruby-kafka. So, I'm thinking that this issue is from another place. From the logs, the client is able to connect to the server to get metadata of the cluster, but the cluster returns empty node list. Therefore, I'm thinking there is an issue with your kafka cluster. Could you debug the issue with Kafka Manager, or Kafka commandline, or official kafka client in Java?

**Comment by J2RGEZ** [comment]
I've been testing this and this was a bad configuration of my brokers (I'm using kafka-docker). Closing this :dancer:

**Comment by daanemanz** [comment]
@juanjoman It's a little while ago, but could you elaborate on what you did on your brokers to fix this?

**Comment by juanjoman** [comment]
hey hi @daanemanz, absolutely! Here is my docker-compose.yml file (that makes everything working now):

```
version: '2'
services:
  zookeeper:
   image: wurstmeister/zookeeper
   ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: <my_wifi_ip>
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9093:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: <my_wifi_ip>
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9094:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: <my_wifi_ip>
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Sometimes I have to reset this twice but in general, I do:

1. `docker-compose stop` and `docker-compose rm` to make sure I clean everything
2. `docker-compose up -d`. Remove the -d to see Kafka low-level logs.
